### ISSUE TITLE
execution problem

### ISSUE THREAD

**Issue by psdjc** [KaffinPX/Kaspool#1]
root@t320:/usr/local/src/Kaspool# node index.js 
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module './wasm/kaspa_wasm'
Require stack:
- /usr/local/src/Kaspool/src/kaspa/index.js
- /usr/local/src/Kaspool/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/src/Kaspool/src/kaspa/index.js:3:55)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/src/Kaspool/src/kaspa/index.js',
    '/usr/local/src/Kaspool/index.js'
  ]
}

**Comment by KaffinPX** [comment]
You need to import WASM built from aspectrons rusty-kaspa which is known to be not stable yet, thats why its called experimental.
