### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by crmiman** [KaffinPX/Kaspool#3]
Hi, i have this issue, while trying to run pool. Can you help me?

`node -v`
`v20.10.0`

`node index.js`
wasm://wasm/01b5210e:1

RuntimeError: memory access out of bounds
    at wasm://wasm/01b5210e:wasm-function[932]:0x290194
    at wasm://wasm/01b5210e:wasm-function[4525]:0x48ecd9
    at passStringToWasm0 (/home/kas/Kaspool/src/kaspa/wasm/kaspa_wasm.js:162:15)
    at new RpcClient (/home/kas/Kaspool/src/kaspa/wasm/kaspa_wasm.js:5130:26)
    at new Kaspa (/home/kas/Kaspool/src/kaspa/index.js:7:16)
    at Object.<anonymous> (/home/kas/Kaspool/index.js:11:15)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)

**Comment by KaffinPX** [comment]
It is not supported in Node.js.
